### ISSUE TITLE
Detalhes do evento sem acesso deslogado

### ISSUE THREAD

**Issue by renatosoares** [LuanGB/PDS---Eu_Vou#16]
Quando não esta logado não é possível acessar detalhes o evento, também ocorre quando mesmo logado tenta acessar outro evento que não foi criado

**Comment by marceloodir** [comment]
Não entendi direito, tem como postar screenshots dos problema?

**Comment by renatosoares** [comment]
![captura de tela de 2015-08-08 21 44 39](https://cloud.githubusercontent.com/assets/2559693/9152997/d410a83c-3e16-11e5-9e71-2092528ca294.png)

**Comment by renatosoares** [comment]
![captura de tela de 2015-08-08 21 44 39](https://cloud.githubusercontent.com/assets/2559693/9153000/239e3630-3e17-11e5-936a-f21f52914032.png)

isso é o que ocorre quando tento acessar um evento sem esta logado no sistema. 
Podemos ver isso segunda pois não esta atrapalhando meu desenvolvimento. :thumbsup:

**Comment by marceloodir** [comment]
Esse problema tá ocorrendo no branch issue_comments?

**Comment by marceloodir** [comment]
Bug solucionado com o commit 86b052b8c5e6e6421f4235ff1f4aa9620d8bbe64 no branch Issue_comments, por favor verifique.

**Comment by renatosoares** [comment]
blz, vou verificar amanhã de manhã.

**Comment by renatosoares** [comment]
Resolvido
